version: '2'
services:
 slave:
   build: ./slave
   expose:
     - "8088"
 master:
    build: ./master

    environment:
      - WRK_NODE=1 

    volumes:
      - .:/master

    links:
     - "slave"
